// src/components/PayslipModal.jsx
import { useEffect } from 'react'
import { createPortal } from 'react-dom'
import { fmtSGD, MONTH_NAMES } from '../utils/payroll'

export default function PayslipModal({ record, companyName, logoUrl, language, onClose }) {
  const zh = language === 'zh'
  const m  = record
  const monthShort = MONTH_NAMES[m.month]?.slice(0, 3)
  const monthLabel = `${MONTH_NAMES[m.month]?.toUpperCase()} ${m.year}`

  useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [])

  function handlePrint() {
    const safeName = (m.snap_name || 'Employee')
      .replace(/[^a-zA-Z0-9\s]/g, '').trim().replace(/\s+/g, '_')
    const originalTitle = document.title
    document.title = `${safeName}_Payslip_${monthShort}${m.year}`
    window.print()
    setTimeout(() => { document.title = originalTitle }, 1000)
  }

  const earningRows = [
    { label: 'Basic Salary',                                    val: m.basic_salary,          ytd: m.ytd_basic            },
    { label: 'Allowance',                                       val: m.fixed_allowance,       ytd: m.ytd_fixed_allowance  },
    { label: m.other_allowance_desc||'Other Allowance',         val: m.other_allowance,       ytd: m.ytd_other_allowance,   show: m.other_allowance > 0 },
    { label: m.overtime_desc||'Over Time / Other',              val: m.overtime,              ytd: m.ytd_overtime,          show: m.overtime > 0 },
    { label: m.bonus_desc||'Bonus',                             val: m.bonus,                 ytd: m.ytd_bonus,             show: m.bonus > 0 },
    { label: 'Commission',                                      val: m.commission,            ytd: m.ytd_commission,        show: m.commission > 0 },
    { label: m.director_fee_desc||'Director Fee',               val: m.director_fee,          ytd: m.ytd_director_fee,      show: m.director_fee > 0 },
    { label: m.unutilised_leave_desc||'Unutilised Pay Leave',   val: m.unutilised_leave_pay,  ytd: m.ytd_unutilised_leave,  show: m.unutilised_leave_pay > 0 },
    { label: 'Unpaid Leave', val: -(m.unpaid_leave_amount||0),  ytd: -(m.ytd_unpaid_leave||0), neg: true, show: m.unpaid_leave_amount > 0 },
  ].filter(r => r.show !== false)

  const adjustments = Array.isArray(m.other_adjustments) ? m.other_adjustments : []
  const ytdTotalDeduction = (m.ytd_employee_cpf||0) + (m.ytd_cdac||0)
  const footer = `This payslip is system-generated by ${companyName} HR System. No signature required.`

  const content = (
    <div style={{fontFamily:'Arial,Helvetica,sans-serif',fontSize:'11px',color:'#111',background:'white',maxWidth:'680px'}}>
      {/* Header */}
      <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:8}}>
        {logoUrl && <img src={logoUrl} alt="logo" style={{height:44,objectFit:'contain',maxWidth:140}}/>}
        <div style={{fontWeight:'bold',fontSize:13}}>{companyName}</div>
      </div>
      {/* Title */}
      <div style={{textAlign:'center',fontWeight:'bold',fontSize:15,borderBottom:'2px solid #222',paddingBottom:6,marginBottom:10}}>
        Payslip for {monthLabel}
      </div>
      {/* Info box */}
      <div style={{display:'flex',border:'1px solid #ccc',marginBottom:10,fontSize:10}}>
        <div style={{padding:'6px 10px',flex:1,lineHeight:1.8}}>
          <div><b>Name:</b> {m.snap_name}</div>
          <div><b>NRIC / FIN:</b> {m.snap_nric||'—'}</div>
          <div><b>Position:</b> {m.snap_position||'—'}</div>
        </div>
        <div style={{padding:'6px 10px',textAlign:'right',borderLeft:'1px solid #ccc',lineHeight:1.8}}>
          <div>Page 1 of 1</div>
          <div><b>Basic Salary:</b> {fmtSGD(m.basic_salary)}</div>
          <div><b>Commencement Date:</b> {m.snap_join_date||'—'}</div>
          <div><b>Last Date:</b></div>
        </div>
      </div>
      {/* Table */}
      <table style={{width:'100%',borderCollapse:'collapse',fontSize:'10px'}}>
        <tbody>
          <tr style={{background:'#eee'}}>
            <td style={{padding:'4px 6px',width:'55%',fontWeight:'bold'}}></td>
            <td style={{padding:'4px 6px',textAlign:'right',width:'22%',fontWeight:'bold'}}>SGD</td>
            <td style={{padding:'4px 6px',textAlign:'right',width:'23%',fontWeight:'bold'}}>YTD (SGD)</td>
          </tr>
          {/* Earnings section */}
          <tr><td colSpan={3} style={{fontWeight:600,padding:'6px 6px 2px',color:'#444'}}>Earnings</td></tr>
          {earningRows.map((r,i)=>(
            <tr key={i}>
              <td style={{padding:'2.5px 6px 2.5px 14px',color:'#444'}}>{r.label}</td>
              <td style={{padding:'2.5px 6px',textAlign:'right',color:r.neg?'#bb0000':'inherit'}}>
                {r.neg ? (Math.abs(r.val)>0?`( ${fmtSGD(Math.abs(r.val))} )`:'0.00') : fmtSGD(r.val)}
              </td>
              <td style={{padding:'2.5px 6px',textAlign:'right',color:'#888'}}>
                {r.neg ? (Math.abs(r.ytd)>0?`( ${fmtSGD(Math.abs(r.ytd))} )`:'0.00') : fmtSGD(r.ytd||0)}
              </td>
            </tr>
          ))}
          <tr style={{borderTop:'1px dashed #aaa'}}>
            <td style={{padding:'4px 6px 4px 14px',fontWeight:'bold'}}>Total Earnings</td>
            <td style={{padding:'4px 6px',textAlign:'right',fontWeight:'bold'}}>{fmtSGD(m.gross_salary)}</td>
            <td style={{padding:'4px 6px',textAlign:'right',fontWeight:'bold',color:'#888'}}>{fmtSGD(m.ytd_gross||0)}</td>
          </tr>
          {/* Deductions */}
          <tr><td colSpan={3} style={{fontWeight:600,padding:'6px 6px 2px',color:'#444'}}>Deductions</td></tr>
          {m.employee_cpf>0&&<tr>
            <td style={{padding:'2.5px 6px 2.5px 14px',color:'#444'}}>Employee CPF</td>
            <td style={{padding:'2.5px 6px',textAlign:'right',color:'#bb0000'}}>( {fmtSGD(m.employee_cpf)} )</td>
            <td style={{padding:'2.5px 6px',textAlign:'right',color:'#888'}}>( {fmtSGD(m.ytd_employee_cpf||0)} )</td>
          </tr>}
          {m.cdac_mbmf_sinda>0&&<tr>
            <td style={{padding:'2.5px 6px 2.5px 14px',color:'#444'}}>CDAC/ MBMF/ SINDA Fund</td>
            <td style={{padding:'2.5px 6px',textAlign:'right',color:'#bb0000'}}>( {fmtSGD(m.cdac_mbmf_sinda)} )</td>
            <td style={{padding:'2.5px 6px',textAlign:'right',color:'#888'}}>( {fmtSGD(m.ytd_cdac||0)} )</td>
          </tr>}
          <tr style={{borderTop:'1px dashed #aaa'}}>
            <td style={{padding:'4px 6px 4px 14px',fontWeight:'bold'}}>Total Deduction</td>
            <td style={{padding:'4px 6px',textAlign:'right',fontWeight:'bold',color:'#bb0000'}}>( {fmtSGD(m.total_deduction)} )</td>
            <td style={{padding:'4px 6px',textAlign:'right',fontWeight:'bold',color:'#888'}}>( {fmtSGD(ytdTotalDeduction)} )</td>
          </tr>
          {/* Net Pay */}
          <tr style={{background:'#f0f4ff'}}>
            <td style={{padding:'5px 6px',fontWeight:'bold',fontSize:11}}><b>Net Pay</b></td>
            <td style={{padding:'5px 6px',textAlign:'right',fontWeight:'bold',color:'#1d4ed8',fontSize:11}}><b>{fmtSGD(m.net_pay)}</b></td>
            <td style={{padding:'5px 6px',textAlign:'right',fontWeight:'bold',color:'#888'}}><b>{fmtSGD(m.ytd_net_pay||0)}</b></td>
          </tr>
          {/* Other Adjustments */}
          {adjustments.length>0&&<>
            <tr><td colSpan={3} style={{fontWeight:600,padding:'6px 6px 2px',color:'#444'}}>Other Deduction / Adjustment</td></tr>
            {adjustments.map((a,i)=>(
              <tr key={i}>
                <td style={{padding:'2.5px 6px 2.5px 14px',color:'#444'}}>{a.desc||'—'}</td>
                <td style={{padding:'2.5px 6px',textAlign:'right',color:Number(a.amount)<0?'#bb0000':'#166534'}}>
                  {Number(a.amount)<0?`( ${fmtSGD(Math.abs(a.amount))} )`:fmtSGD(a.amount)}
                </td>
                <td style={{padding:'2.5px 6px',textAlign:'right',color:'#888'}}>—</td>
              </tr>
            ))}
            <tr style={{borderTop:'1px dashed #aaa'}}>
              <td style={{padding:'4px 6px',fontWeight:'bold'}}><b>Net Pay after other deduction</b></td>
              <td style={{padding:'4px 6px',textAlign:'right',fontWeight:'bold',color:'#1d4ed8'}}><b>{fmtSGD(m.net_pay_after_adjustments)}</b></td>
              <td style={{padding:'4px 6px',textAlign:'right',color:'#888'}}>—</td>
            </tr>
          </>}
          {/* Spacer */}
          <tr><td colSpan={3} style={{padding:'4px 0'}}></td></tr>
          {/* Employer costs */}
          {m.employer_cpf>0&&<tr style={{background:'#f7f7f7'}}>
            <td style={{padding:'3px 6px 3px 14px',color:'#444'}}>Employer CPF</td>
            <td style={{padding:'3px 6px',textAlign:'right'}}>{fmtSGD(m.employer_cpf)}</td>
            <td style={{padding:'3px 6px',textAlign:'right',color:'#888'}}>{fmtSGD(m.ytd_employer_cpf||0)}</td>
          </tr>}
          <tr style={{background:'#f7f7f7'}}>
            <td style={{padding:'3px 6px 3px 14px',color:'#444'}}>SDL</td>
            <td style={{padding:'3px 6px',textAlign:'right'}}>{fmtSGD(m.sdl)}</td>
            <td style={{padding:'3px 6px',textAlign:'right',color:'#888'}}>{fmtSGD(m.ytd_sdl||0)}</td>
          </tr>
          {m.fwl>0&&<tr style={{background:'#f7f7f7'}}>
            <td style={{padding:'3px 6px 3px 14px',color:'#444'}}>Foreign Worker Levy (FWL)</td>
            <td style={{padding:'3px 6px',textAlign:'right'}}>{fmtSGD(m.fwl)}</td>
            <td style={{padding:'3px 6px',textAlign:'right',color:'#888'}}>{fmtSGD(m.ytd_fwl||0)}</td>
          </tr>}
          <tr style={{background:'#dbeafe',borderTop:'2px solid #2563eb'}}>
            <td style={{padding:'5px 6px 5px 14px',fontWeight:'bold',color:'#1d4ed8'}}><b>Total Company Paid</b></td>
            <td style={{padding:'5px 6px',textAlign:'right',fontWeight:'bold',color:'#1d4ed8'}}><b>{fmtSGD(m.total_company_paid)}</b></td>
            <td style={{padding:'5px 6px',textAlign:'right',fontWeight:'bold',color:'#888'}}><b>{fmtSGD(m.ytd_total_company_paid||0)}</b></td>
          </tr>
        </tbody>
      </table>
      {/* Bank info */}
      <div style={{borderTop:'1px solid #ccc',paddingTop:8,marginTop:10,fontSize:10,color:'#555'}}>
        <div><b>To Be Credited to</b></div>
        <table style={{fontSize:10,marginTop:3}}>
          <tbody>
            <tr>
              <td style={{paddingRight:16,color:'#666'}}>Bank Name:</td>
              <td>{m.snap_bank_name||'—'}</td>
              <td style={{paddingLeft:24,color:'#666'}}>Bank Code:</td>
              <td></td>
            </tr>
            <tr>
              <td style={{color:'#666'}}>Account Number:</td>
              <td style={{fontFamily:'monospace'}}>{m.snap_bank_account_no||'—'}</td>
              <td style={{paddingLeft:24,color:'#666'}}>Branch Code:</td>
              <td></td>
            </tr>
          </tbody>
        </table>
        {m.payment_date&&<div style={{marginTop:4}}>On {m.payment_date}</div>}
      </div>
      {/* Footer */}
      <div style={{marginTop:14,borderTop:'1px solid #eee',paddingTop:6,fontSize:9,color:'#999',textAlign:'center'}}>
        {footer}<br/>Generated on: {new Date().toLocaleString()}
      </div>
    </div>
  )

  return (
    <>
      <style>{`
        @media print {
          html,body{margin:0;padding:0;}
          body>*{display:none!important;}
          #ps-print-root{display:block!important;position:fixed;top:0;left:0;width:100%;padding:15mm;}
          @page{size:A4 portrait;margin:0;}
        }
        #ps-print-root{display:none;}
      `}</style>
      {/* Hidden print copy */}
      {createPortal(<div id="ps-print-root">{content}</div>, document.body)}
      {/* Screen modal */}
      <div className="fixed inset-0 bg-black/60 z-50 flex items-start justify-center overflow-y-auto py-6">
        <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl mx-4">
          <div className="flex justify-between items-center px-5 py-3 border-b border-gray-100 sticky top-0 bg-white rounded-t-xl z-10">
            <span className="font-semibold text-gray-700 text-sm">
              {zh?'工資單預覽':'Payslip Preview'} — {m.snap_name} · {monthLabel}
            </span>
            <div className="flex gap-2">
              <button onClick={handlePrint}
                className="px-4 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 flex items-center gap-1.5">
                🖨️ {zh?'打印 / 存為 PDF':'Print / Save PDF'}
              </button>
              <button onClick={onClose}
                className="px-3 py-1.5 text-gray-500 border border-gray-200 text-sm rounded-lg hover:bg-gray-50">✕</button>
            </div>
          </div>
          <div className="p-6 bg-gray-50">
            <div className="bg-white border border-gray-200 rounded-lg p-5 shadow-sm overflow-x-auto">
              {content}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}